name: Multi-Container-Deployment

on:
    push:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 
            - run: docker build -t thanhphuocnguyen897/react-test -f ./client/Dockerfile.dev ./client
            - run: docker run CI=true thanhphuocnguyen897/react-test npm test
            - run: docker build -t thanhphuocnguyen897/m-c-client ./client
            - run: docker build -t thanhphuocnguyen897/m-c-server ./server
            - run: docker build -t thanhphuocnguyen897/m-c-worker ./worker
            - run: docker build -t thanhphuocnguyen897/m-c-nginx ./nginx
            - run: docker push thanhphuocnguyen897/m-c-client
            - run: docker push thanhphuocnguyen897/m-c-server
            - run: docker push thanhphuocnguyen897/m-c-worker
            - run: docker push thanhphuocnguyen897/m-c-nginx